[project]
name = "rage-web"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "flask>=3.1.1",
    "flask-migrate>=4.1.0",
    "flask-sqlalchemy>=3.1.1",
    "flask-wtf>=1.2.2",
    "python-slugify>=8.0.4",
    "python-telegram-bot>=22.8",
]

[tool.setuptools.packages]
find = {}

[project.scripts]
rage-match = "rage_web.game_engine.match:main"
rage-cli = "rage_web.game_engine.cli:main"
rage-bot = "rage_web.telegram_bot.bot:main"

[dependency-groups]
dev = [
    "pytest>=8.4.1",
]
