"""adiciona galeria social de decks

Revision ID: 5dfa67153220
Revises: 6184382ced8d
Create Date: 2026-06-13 21:57:11.543373

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5dfa67153220'
down_revision = '6184382ced8d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deck', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_public', sa.Boolean(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('telegram_owner_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('usage_count', sa.Integer(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deck', schema=None) as batch_op:
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')
        batch_op.drop_column('usage_count')
        batch_op.drop_column('telegram_owner_id')
        batch_op.drop_column('is_public')

    # ### end Alembic commands ###
