"""adiciona content_hash ao deck

Revision ID: 612cc7a87fac
Revises: 89360bde20a8
Create Date: 2026-08-15 09:30:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '612cc7a87fac'
down_revision = '89360bde20a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deck', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content_hash', sa.String(length=64),
                                      server_default='', nullable=False))
        batch_op.create_index(batch_op.f('ix_deck_content_hash'),
                              ['content_hash'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deck', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_deck_content_hash'))
        batch_op.drop_column('content_hash')

    # ### end Alembic commands ###
