"""Adiciona campos grupos+mata-mata ao torneio

Revision ID: 6184382ced8d
Revises: c9f84a5766ef
Create Date: 2026-06-11 14:52:31.402457

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6184382ced8d'
down_revision = 'c9f84a5766ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tournament', schema=None) as batch_op:
        batch_op.add_column(sa.Column('num_groups', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('advance_per_group', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('group_stage_finished', sa.Boolean(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('bracket_json', sa.Text(), nullable=False, server_default=''))

    with op.batch_alter_table('tournament_player', schema=None) as batch_op:
        batch_op.add_column(sa.Column('group', sa.Integer(), nullable=False, server_default='0'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tournament_player', schema=None) as batch_op:
        batch_op.drop_column('group')

    with op.batch_alter_table('tournament', schema=None) as batch_op:
        batch_op.drop_column('bracket_json')
        batch_op.drop_column('group_stage_finished')
        batch_op.drop_column('advance_per_group')
        batch_op.drop_column('num_groups')

    # ### end Alembic commands ###
