"""adiciona renown_cap e strategy ao deck

Revision ID: 89360bde20a8
Revises: 5dfa67153220
Create Date: 2026-06-19 02:19:03.803323

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89360bde20a8'
down_revision = '5dfa67153220'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('card', schema=None) as batch_op:
        batch_op.alter_column('text',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=False)

    with op.batch_alter_table('deck', schema=None) as batch_op:
        batch_op.add_column(sa.Column('renown_cap', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('strategy', sa.String(length=20), server_default='midrange', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deck', schema=None) as batch_op:
        batch_op.drop_column('strategy')
        batch_op.drop_column('renown_cap')

    with op.batch_alter_table('card', schema=None) as batch_op:
        batch_op.alter_column('text',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=False)

    # ### end Alembic commands ###
