"""adiciona fan_image ao Card

Revision ID: b80dd916bd48
Revises: d103d7ec1298
Create Date: 2026-06-03 23:18:05.667012

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b80dd916bd48'
down_revision = 'd103d7ec1298'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('card', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fan_image', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('card', schema=None) as batch_op:
        batch_op.drop_column('fan_image')

    # ### end Alembic commands ###
