"""Adiciona campos expansion, deck_cards e importacao

Revision ID: d103d7ec1298
Revises: 6bda8104262a
Create Date: 2026-06-03 17:51:09.258771

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd103d7ec1298'
down_revision = '6bda8104262a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deck_cards',
    sa.Column('deck_id', sa.Integer(), nullable=False),
    sa.Column('card_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['card_id'], ['card.id'], ),
    sa.ForeignKeyConstraint(['deck_id'], ['deck.id'], ),
    sa.PrimaryKeyConstraint('deck_id', 'card_id')
    )
    with op.batch_alter_table('card', schema=None) as batch_op:
        batch_op.add_column(sa.Column('expansion', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('image_file', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('sealed', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('notes', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('renown', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('damage', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('errata', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('card', schema=None) as batch_op:
        batch_op.drop_column('errata')
        batch_op.drop_column('damage')
        batch_op.drop_column('renown')
        batch_op.drop_column('notes')
        batch_op.drop_column('sealed')
        batch_op.drop_column('image_file')
        batch_op.drop_column('expansion')

    op.drop_table('deck_cards')
    # ### end Alembic commands ###
